### ISSUE TITLE
Create todo-list page

### ISSUE THREAD

**Issue by Iorg** [Iorg/todo-app#2]
Need to create a new page that will show all TODOs. 

Specification:
1. Create a new file `all-todos.html`;
2. Open that file for edit;
3. Put standard html markup by typing `html:5` and press enter;
4. Add to the index.html page the following markup: 
```html
<a href="all-todos.html">View all todos</a>
```
5. Save, commit and sync your changes.

**Comment by AnnaKira** [comment]
@Iorg Help me with 3'rd unit.

**Comment by amoreoni** [comment]
done!

**Comment by AnnaKira** [comment]
@Iorg  test
