### ISSUE TITLE
Make simple markup for all-todos page

### ISSUE THREAD

**Issue by Iorg** [Iorg/todo-app#5]
Add simple markup for all-todos page:

1. Add simple text label with `<h1></h1>` tag: All todos
2. Add text input control with label:
```html
<ul>
  <li>Cras justo odio</li>
  <li>Dapibus ac facilisis in</li>
  <li>Morbi leo risus</li>
  <li>Porta ac consectetur ac</li>
  <li>Vestibulum at eros</li>
</ul>
```
> Hint. You can use VS Code's autocomplete function. For example in you type `ul>li*5` and press enter and the whole html tag will appear.
3. Add link to add-todo page: `<a href="add-todo.html">Add todo</a>`. (or if you have some better idea how to call it, fell free 😄 )

**Comment by Iorg** [comment]
@amoreoni Fill free to add any styling, btw

**Comment by amoreoni** [comment]
done!
